### ISSUE TITLE
ViewPager2如何使用比较复杂的布局呢？

### ISSUE THREAD

**Issue by dingxiansen1** [crazyqiang/AndroidStudy#8]

**Comment by dingxiansen1** [comment]
我看了一下API，发现setLoader这个方法可以实现item自定义样式，但是如果item样式比较复杂，如何像原来adapter那样使用xml来写布局，因为item要根据数据不同的来展示不同的节目，比如图片加上标题 1/5 标题XXXX，如何实现这个的item？如果更复杂呢？有更方便的API提供吗？

**Comment by crazyqiang** [comment]
> 的

1、复杂的布局可以用xml的 继承baseloader并重写createview即可 代码中给的示例是直接用代码写的，另外你说的更复杂的场景 是说根据数据的不用展示的每个Item的样式也不同这种场景是吗 实际会有这种需求吗 或者是否可以发一下你的UI样式  
2、标题 1/5 标题XXXX 这种是指的指示器吗，这个目前指示器样式比较单一，没有对外暴露，后续版本中会进行改进

**Comment by crazyqiang** [comment]
> 我看了一下API，发现setLoader这个方法可以实现item自定义样式，但是如果item样式比较复杂，如何像原来adapter那样使用xml来写布局，因为item要根据数据不同的来展示不同的节目，比如图片加上标题 1/5 标题XXXX，如何实现这个的item？如果更复杂呢？有更方便的API提供吗？

1、复杂的布局可以用xml的 继承baseloader并重写createview即可 代码中给的示例是直接用代码写的，另外你说的更复杂的场景 是说根据数据的不用展示的每个Item的样式也不同这种场景是吗 实际会有这种需求吗 或者是否可以发一下你的UI样式
2、标题 1/5 标题XXXX 这种是指的指示器吗，这个目前指示器样式比较单一，没有对外暴露，后续版本中会进行改进

**Comment by dingxiansen1** [comment]
复杂的布局可以用xml的 继承baseloader并重写createview  
如何绑定xml布局文件呢（是通过databinding还是什么？），可以弄简单的事例吗？感谢大佬

**Comment by crazyqiang** [comment]
> 复杂的布局可以用xml的 继承baseloader并重写createview
> 如何绑定xml布局文件呢（是通过databinding还是什么？），可以弄简单的事例吗？感谢大佬

示例可以下载最新的代码 看这个自定义Loader类：CustomItemLoader，完整实现在MVP2MultiItemFragment中

**Comment by crazyqiang** [comment]
> 复杂的布局可以用xml的 继承baseloader并重写createview
> 如何绑定xml布局文件呢（是通过databinding还是什么？），可以弄简单的事例吗？感谢大佬

没有制作最新的apk，可以下载最新的代码运行下  看是否符合你的需求
